name: Published release workflow

on:
  release:
    types:
      - published

jobs:
  print-value:
    runs-on: ubuntu-latest
    steps:
      - name: Print value published
        run: echo "published release"
  